// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_dummysndmngr[] =
"<?xml version=\"1.0\"?>"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.planeshift.sound.dummy</name>"
"        <implementation>DummySoundManager</implementation>"
"        <description>Dummy Sound Manager</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef DummySoundManager_FACTORY_REGISTER_DEFINED 
  #define DummySoundManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(DummySoundManager) 
  #endif

class dummysndmngr
{
SCF_REGISTER_STATIC_LIBRARY(dummysndmngr,metainfo_dummysndmngr)
  #ifndef DummySoundManager_FACTORY_REGISTERED 
  #define DummySoundManager_FACTORY_REGISTERED 
    DummySoundManager_StaticInit DummySoundManager_static_init__; 
  #endif
public:
 dummysndmngr();
};
dummysndmngr::dummysndmngr() {}

}
