// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_dbmysql[] =
"<?xml version=\"1.0\"?>"
"<!-- dbmysql.csplugin -->"
"<plugin>"
"  <name>dbmysql</name>"
"  <scf>"
"    <classes>      "
"      <class>"
"        <name>planeshift.database.mysql</name>"
"        <implementation>psMysqlConnection</implementation>"
"	    <description>psDatabase database plugin</description>"
"      </class>"
"    </classes>"
"  </scf>    "
"</plugin>";
  #ifndef psMysqlConnection_FACTORY_REGISTER_DEFINED 
  #define psMysqlConnection_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(psMysqlConnection) 
  #endif

class dbmysql
{
SCF_REGISTER_STATIC_LIBRARY(dbmysql,metainfo_dbmysql)
  #ifndef psMysqlConnection_FACTORY_REGISTERED 
  #define psMysqlConnection_FACTORY_REGISTERED 
    psMysqlConnection_StaticInit psMysqlConnection_static_init__; 
  #endif
public:
 dbmysql();
};
dbmysql::dbmysql() {}

}
